### ISSUE TITLE
Lack of support for the walrus operator.

### ISSUE THREAD

**Issue by freak-js** [wemake-services/wemake-python-styleguide#1098]
Here is an example of the error that the linter points to:

`E701  multiple statements on one line (colon)
  if distributor_id := validate_id(request.POST.get('distributor_id')):
`

If this is not a bug, but a feature, then please correct me (I just started using your linter).

**Comment by sobolevn** [comment]
@freak-js thanks a lot for this bug report! Currently we do not support `python3.8` at all. Because we need to upgrade multiple dependencies and fix a lot of stuff inside. You can track these issues:
- https://github.com/wemake-services/wemake-python-styleguide/milestone/10

By the way, using walrus operator will be not allowed in `0.14`, see: 
- #34 

I am closing this one, however, feel free to ask any questions you have or provide any feedback you have. Thanks!
