### ISSUE TITLE
Forbid to have too many raise statements

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#1160]
# Rule request

## Thesis

Currently we check for a lot of function internals.
But, one can write any number of `raise MyError` statements. It is not checked at all.

We need to create new `TooManyRaisesViolation` with configuration to be able to find these problems. I can suggest to use `4` as maximum amount of `raise` uses. Or even `3`.

This is a complexity violation.

**Comment by iZafiro** [comment]
Hi! Can I take this issue? Thanks!

**Comment by sobolevn** [comment]
Sure! Thank you! Make sure to read [our contributing guides](https://github.com/wemake-services/wemake-python-styleguide/blob/master/CONTRIBUTING.md)

I am here to help: ask anything you need.

**Comment by iZafiro** [comment]
Hi! I've written the code by improving upon the `_ComplexityCounter class` in `visitors\ast\complexity\function.py` by adding an extra public attribute that counts the number of raise statements within a function. However, I get a lint error because the linter finds too many public attributes. If I change the` MAX_ATTRIBUTES` default (by one), the tests for `TooManyPublicAttributesViolation` fail. I was thinking that the best solution may be to make the linter ignore the class, so how can I do that? Thanks so much!

**Comment by sobolevn** [comment]
@iZafiro no, complexity violations generally should not be ignored. Instead, we should refactor our class to be simplier. Here's our policy: https://sobolevn.me/2019/10/complexity-waterfall

I see several solutions:
1. We can split `_ComplexityCounter` into several classes and refactor how it is used
2. We can change how properties are defined. For example you can create `@final @dataclass class _ComplexityMetrics(object)` with fields that you need.

Does this sound fine to you? 🙂

**Comment by iZafiro** [comment]
@sobolevn Yeah, I'll refactor the class then. :)
