### ISSUE TITLE
Jones complexity is a part of main checks?

### ISSUE THREAD

**Issue by Niccolum** [wemake-services/wemake-python-styleguide#1346]
I think, it's strange, that some checks, for example Jones Complexity is a part of big mechanism for checking wemake-python-styleguide, if it must be separate plagin, isn't it? Why you do not to maintain it separately of main program?

**Comment by sobolevn** [comment]
That's a good question! 

Because I try to get rid of any unwanted dependencies. My motivation behind this is that extra packages requires extra effort: releasing, updating, maintaining them. This is a hard thing to do! 

Moreover, separating cool stuff from the core project is not a good idea from the marketing point. Currently you can have all or none. And that's the whole idea of this linter.

I hope you share my vision now 🙂

**Comment by Niccolum** [comment]
Yes, thanks
