### ISSUE TITLE
Consider allowing walrus operator in while loop and comprehensions

### ISSUE THREAD

**Issue by Dreamsorcerer** [wemake-services/wemake-python-styleguide#1442]
The walrus operator can reduce code complexity if used correctly. Maybe consider allowing it in a couple of use cases.

In a while loop, this avoids duplication of code:
```
while line := await reader.readline():
    ...
```
would need to be written as:
```
line = await reader.readline()
while line:
    ...
    line = await reader.readline()
```
Which results in duplicated code, and moves the conditional code away from the while loop definition.

Another example from the Python release notes:
> Another motivating use case arises in list comprehensions where a value computed in a filtering condition is also needed in the expression body:
```
[clean_name.title() for name in names
 if (clean_name := normalize('NFC', name)) in allowed_names]
```

In this case it's avoiding making a second call to the `normalize()` function, thus creating more efficient code.

I think the `if` statements are a little questionable, but in while loops and comprehensions, it can produce better code.

**Comment by sobolevn** [comment]
Thanks a lot for bringing this up! 

Is is a very hard thing to discuss. Because it is very opinionated. 
And I personally really (really!) dislike walrus operator. 

I don't see any problem when people disable this check in their own code, but I don't want to support any other checks except the one we already have: no walrus. 

I guess, it might be a great idea for another plugin! I haven't seen any good walrus-specific rules yet. 

If you find (create) any, I would be happy to provide a link to it from our docs. 👍 

Closing this as `wontfix`.

**Comment by Dreamsorcerer** [comment]
OK, no problem.

For me, whenever I've written a while loop like that example, even long before the walrus operator, I would stare at the loop for atleast several minutes trying to see if there is a cleaner way to write it, without duplicating code.

There is also no way to write that comprehsion example efficiently without walrus. You either have to call the function twice, or write it without a comprehension, both of which would result in less efficient code.

**Comment by Dreamsorcerer** [comment]
Also worth mentioning. The doc says "Python is not expression-based."

However, it looks like Python 3.9 is:
https://www.python.org/dev/peps/pep-0617/#background-on-peg-parsers
