### ISSUE TITLE
WPS305 Rationale suggestion

### ISSUE THREAD

**Issue by nymann** [wemake-services/wemake-python-styleguide#1522]
It's my personal opinion that incorporating your own words in the `readme.md`
> Enforce "There should be one -- and preferably only one -- obvious way to do it"

As a rationale for WPS305 is overall better.

To me (a newcomer) the current rationale in issue #32 comes of as "it's hard to lint so let's not bother". While saying there should only be one way to do something and in the case of formatting strings that's `.format()` is something I can get behind.

What do you think?

**Comment by sobolevn** [comment]
I am open to suggestions and pull requests! 🥇

**Comment by jtpavlock** [comment]
Perhaps with the changes in https://github.com/wemake-services/wemake-python-styleguide/pull/1315 a configuration option to only prefer f strings could be allowed? The use of a string formatter between f strings and .format() seems highly subjective and I don't think there is "an obvious way to do it".

**Comment by sobolevn** [comment]
`f` strings are fundamentally more complex than `.format`, because:
- they implicitly rely on the context: `f'My name is {name}'`. Try to rename `name` variable outside of the string literal and it will blow.
- they do two things at once: defining the template and formatting it

So, `f` strings would never be the default. But, you can switch rules you don't like and use a custom `flake8` plugin to enforce `f` strings in your own projects.
