### ISSUE TITLE
WPS306 seems outdated

### ISSUE THREAD

**Issue by Dreamsorcerer** [wemake-services/wemake-python-styleguide#1559]
WPS306 requires inheriting from `object`. This seems like a rather dated approach for Python 3 code.

The doc has a 'See also' link which further proves the point and contradicts the wemake rule, saying that it's preferable without `object`, and lists the other approach as 'Ancient'.

**Comment by orsinium** [comment]
I'm even in favor of making the opposite rule: "don't inherit a class from `object`, it's no use in Python 3"

**Comment by sobolevn** [comment]
For some reason Python developers are incorrectly interpreting this rule. (Maybe because of the damaging past)

The idea of this rule is not about `python2` vs `python3`. It is about consistency of `class A(object):` vs `class B(A):`
We always have our base class in `()`.

That's it. Please, don't search any historic issues here.

**Comment by Dreamsorcerer** [comment]
OK, but that's not clear from the text. I expect the "See also" to help confirm the reasoning, but here it directly contradicts the rule.

**Comment by sobolevn** [comment]
Yes, docs can be misleading and should be fixed! Thanks!
