### ISSUE TITLE
WPS update policy with dependencies updates

### ISSUE THREAD

**Issue by zyrikby** [wemake-services/wemake-python-styleguide#1569]
Hi! Thank you for the tool!

I would like to ask what is the policy of updating WPS regarding the updates of the dependencies. I see that dependabot-preview adds commits with dependencies updates, however it is not clear when these updates will appear in WPS version. 

For instance, recently pytest has been updated to version 6.0, and lots of tools now require this version. At the same time, WPS 0.14.1 depends on pytest ^5.4.3. This results in a dependency conflict, e.g., I use poetry and cannot install WPS and pytest-xdist because of this conflict. 

So, what is the best way to proceed in such a situation?

**Comment by sobolevn** [comment]
Hi! @zyrikby 

There are two kinds of dependencies we have:
- dev ones https://github.com/wemake-services/wemake-python-styleguide/blob/master/pyproject.toml#L78 (they are not exported to end users): we update them any time we need. Because, as I said, it does not affect end users. So, your `pytest` example fits in this category. 
- prod ones https://github.com/wemake-services/wemake-python-styleguide/blob/master/pyproject.toml#L53 that are exported to end users. In this case we only make significant update on non-patch (at least minor) releases. 

Currently, we have a lot of new updates in the upcoming `0.15.0`, but I am not sure what the release date would be.
Because for now - I don't have much time working on this project. 
And since it is in a working and reliable state - there's no hurry from our side.

> At the same time, WPS 0.14.1 depends on pytest ^5.4.3. This results in a dependency conflict, e.g., I use poetry and cannot install WPS and pytest-xdist because of this conflict.

Looks like something is wrong on your side. Because, WPS does not require `pytest` for end users. How exactly are you installing this version?

**Comment by zyrikby** [comment]
MWE is the following:

```bash
$ poetry add --dev wemake-python-styleguide pytest-xdist
```

And  this results in a conflict:

```text
[SolverProblemError]
Because no versions of pytest-xdist match >2.0.0,<3.0.0
 and pytest-xdist (2.0.0) depends on pytest (>=6.0.0), pytest-xdist (>=2.0.0,<3.0.0) requires pytest (>=6.0.0).
So, because app depends on both pytest (^5.2) and pytest-xdist (^2.0.0), version solving failed.
```

**Comment by sobolevn** [comment]
Can you please try just `poetry add --dev pytest-xdist`?

It should produce the same output.

**Comment by zyrikby** [comment]
Yep, sorry. For some reason, this is the problem of pytest-xdist. I've tried on a new test project. Sorry once again for bothering you!

**Comment by sobolevn** [comment]
No worries, glad it worked!

**Comment by zyrikby** [comment]
I have found the issue. I have described the solution in a [blog post](https://zhauniarovich.com/post/2020/2020-09-poetry-pytest/). In the future poetry version, this issue will be fixed.

**Comment by sobolevn** [comment]
Great! Thanks for letting me know
