### ISSUE TITLE
Exception for Explicit String Concatenation WPS336

### ISSUE THREAD

**Issue by Sxderp** [wemake-services/wemake-python-styleguide#1606]
# Bug

## Thesis

Allow use of increment operator for appending content to an existing string variable.

```python
# New suggestion
if not uri_path.endswith('/'):
    uri_path += '/'

# With format and reassignment.

# The "correct"? way
if not uri_path.endswith('/'):
    uri_path = '{0}/'.format(uri_path)
```

## Reasoning

It's pretty excessive to have to use format and reassign the variable to append text. Using the increment (is that the right name?) operator is also consistent with WPS350.

**Comment by sobolevn** [comment]
Thanks a lot! This is a very good question!
I would still prefer `uri_path = '{0}/'.format(uri_path)`
Why? Because it shows you the whole operation. It is more noisy, but more visual. 

Moreover, your use-case is really valid. But, what about other ones? Like `+=` a big string? Or multiple `+=`?
So, let's stick to a single way of doing things here.
