### ISSUE TITLE
Pypi release schedule undocumented

### ISSUE THREAD

**Issue by Andrew-Sheridan** [wemake-services/wemake-python-styleguide#1800]
# Bug report

## What's wrong

There does not seem to be a documented release schedule. The current release on pypi is from July 29, 2020. There have been 347 commits to master since that date. When can we expect the next release?

## How it should be

The release schedule should be documented somewhere. (Next release happening: after feature x is finished, on Jan 1st, when bug y is addressed. Etc.

## System information
N/A

### flake8 information

Contents of `flake8 --bug-report`:
N/A

### pip information

Contents of `pip freeze`:
N/A

**Comment by sobolevn** [comment]
Hi!

Thanks for the question! Yes, you are right: the last release was in July. Currently we are working on [`0.15`](https://github.com/wemake-services/wemake-python-styleguide/milestone/19) release.

Unfortunatelly, there's no "schedule". Because this is an open-source project that leverages my and contributors unpaid time. This is how it works: when people have time - they contribute, when they don't - there's no progress made.

There are couple of things you can do to make the release happen faster:
1. Find some issue to fix in https://github.com/wemake-services/wemake-python-styleguide/milestone/19 and send a PR
2. Support us on https://opencollective.com/wemake-python-styleguide

I hope this helps! 

P.S. Happy New Year! 🎄

**Comment by Andrew-Sheridan** [comment]
Thanks for taking the time to respond. 

Happy New Year :)
