### ISSUE TITLE
Split opinionated and usual rules

### ISSUE THREAD

**Issue by AlwxSin** [wemake-services/wemake-python-styleguide#284]
As far as I see there are two types of rules:
* usual ones (like bad variable names, isort style etc.) that most users agree
* breaking ones (like subclassing from object, f-strings etc.) that users can't agree so easy as previous ones

I suggest to split these types into two different codes. `Z` - for breaking, `W` - for usual (you know, `w` for `wemake services`).

So user can ignore whole group of breaking rules. At least, for the beginning.

**Comment by sobolevn** [comment]
@AlwxSin I really like this proposal, since it may increase our users.

But, I have only one question: 

How can we draw the line between opinionated and regular rules? Some people might argue that everything that is not related to the complexity is opinionated. But disabling some checks is really easy to do right now: you can ignore all rules by `Z1`, `Z3`, `Z4`, leaving only complexity checks active.

**Comment by sobolevn** [comment]
@AlwxSin I do not think that voting will work here.
1. Is it a single time vote? This way it won't be representative
2. We will have to vote for each new rule, this will completely ruin all our processes 
3. Constant voting will also ruin the numeration of rules.

I am going to leave this issue open, just in case someone will come up with good ideas.

**Comment by sobolevn** [comment]
@AlwxSin what I came up with: 

1. I can improve the docs to explicitly state how one can ignore errors
2. Add this line to the readme, so it would be easy to find
3. Add these docs to the `django` template as well

So, every person can be sure that at any point in time it is possible to switch off any violations.
