### ISSUE TITLE
Get rid of poetry and replace it with setuptools

### ISSUE THREAD

**Issue by KOLANICH** [wemake-services/wemake-python-styleguide#839]
poetry is not a de-facto-standard build tool and is completely unneeded.

**Comment by sobolevn** [comment]
No, sorry. We use `poetry` for literally all our projects and it works perfectly:
- Manages `venv`
- Works with dependencies
- Stores settings
- Publishes packages

In case you need a `setup.py` file for some reason, you can use: https://github.com/orsinium/poetry-setup or https://github.com/dephell

**Comment by orsinium** [comment]
Poetry is an official alternative to setuptools:

> Consider alternatives to setuptools such as flit, hatch, and poetry.
https://packaging.python.org/tutorials/packaging-projects/

There is no "standard", even de-facto. There are alternatives, and any project free to choose one that fits best for project goals. Setuptools is outdated because doesn't support PEP-517 and PEP-518

**Comment by orsinium** [comment]
You should share your thoughts about what must be standardized, and what's not in [Python mailing list](https://www.python.org/community/lists/), not in a random project. We can't change it for you even if we want. Python changes, do new standards, and community drives such changes through discussions in the right places.

I think, that discussion can be locked.
