### ISSUE TITLE
Forbid `[0:x]` and `[1:None]`, prefer `[:x]` and `[1:]`

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#880]
# Rule request

## Thesis

We need to enforce consistency in several cases:
- `[0:x]` which copies all elements from the first one to `x`. We need to use `[:x]` instead. Because it is way more readable.
- `[1:None]` which copies all elements from the second to the very last one. We need to use `[1:]` instead. It is also more readable.

So, the rule is: we must omit the starting `0` and the leading `None`. Other values are fine.
Step can also be specified:  `[:0:2]` and `[1::2]`

## Reasoning

We do it for consistency reasons.

**Comment by cronos2** [comment]
Can I take this?

**Comment by sobolevn** [comment]
Sure, @cronos2! Thanks a lot!

**Comment by cronos2** [comment]
Great! I believe I have my local setup complete and I'm ready to implement, but I'm not quite sure as to how to approach it.

I think I need to create a new violation as well as a new (AST) visitor (since the only visitor regarding subscripts is about levels/depth in the complexity section, which is not really related to this). Where should I put it, though? Does `operators.py` make sense? Should I create a new file for this?

Any kind of help is appreciated. Thanks!

**Comment by sobolevn** [comment]
Yes, you are 100% correct. That's exactly how it should be done.
